---
    - name: Playbook only supports Debian-based systems
      assert:
        that: "ansible_os_family == '{{ supported_os }}'"

    - name: Install other needed packages
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      tags:
        - packages

    - name: Activate services
      become: true
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
      tags:
        - services