#!/usr/bin/env ansible-playbook
---
    # The -K command line switch is needed to give ansible access to the `sudo` password.
    # Upgrading the operating system requires root access
    - name: Upgrade hosts
      hosts: svcmgmt-docker
      tasks:
        - name: Upgrade system
          apt:
            update_cache: yes
            upgrade: yes