version: '3.7'

services:
  db:
    image: postgres:11-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - dbnet
    restart: on-failure
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: activitylog
      POSTGRES_PASSWORD: activitylog
      POSTGRES_DB: bigdata
    deploy:
      mode: replicated
      replicas: 1
  dbadm:
    depends_on:
      - db
    image: dpage/pgadmin4:latest
    volumes:
      - dbadmdata:/var/lib/pgadmin
    networks:
      - dbnet
    restart: on-failure
    ports:
      - "0.0.0.0:8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: Password1
    deploy:
      mode: replicated
      replicas: 1
  
  websiteblue:
    depends_on:
      - db
    image: marcoh00/activitylog
    networks:
      - dbnet
    restart: on-failure
    ports:
      - "0.0.0.0:21111:80"
    environment:
      DATABASE: Host=db;Database=bigdata;Username=activitylog;Password=activitylog
      COLOR: 0000FF
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.platform.os == linux]
  websitered:
    depends_on:
      - db
    image: marcoh00/activitylog
    networks:
      - dbnet
    restart: on-failure
    ports:
      - "0.0.0.0:21112:80"
    environment:
      DATABASE: Host=db;Database=bigdata;Username=activitylog;Password=activitylog
      COLOR: FF0000
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.platform.os == linux]
  websitegreen:
    depends_on:
      - db
    image: marcoh00/activitylog
    networks:
      - dbnet
    restart: on-failure
    ports:
      - "0.0.0.0:21113:80"
    environment:
      DATABASE: Host=db;Database=bigdata;Username=activitylog;Password=activitylog
      COLOR: 0FFF00
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.platform.os == linux]

  loadbalancer:
    depends_on:
      - websiteblue
      - websitered
      - websitegreen
    image: nginx:stable
    networks:
      - dbnet
    restart: on-failure
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - /vagrant/roles/swarm/files/nginx-loadbalancer.conf:/etc/nginx/nginx.conf
    deploy:
      mode: global

volumes:
  dbdata:
  dbadmdata:

networks:
  dbnet:
    driver: overlay
    attachable: true
  