---
    - name: Create users
      user:
        name: "{{ item.name }}"
        state: present
        append: yes
        create_home: yes
        groups:
          - cdrom
          - sudo
          - floppy
          - audio
          - dip
          - video
          - plugdev
          - netdev
      with_items: "{{ users }}"
    
    - name: Setup SSH authorized_keys
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.sshkey }}"
      with_items: "{{ users }}"
      
    - name: Configure opensshd
      copy:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0640
