---

    - name: Make sure there are no old docker versions around
      become: true
      apt:
        name: "{{ deprecated_docker_pkg }}"
        state: absent
      tags:
        - docker
      
    - name: Install prerequisites for SSL repositories
      become: true
      apt:
        name: "{{ ssl_deps }}"
        state: present
        update_cache: yes
      tags:
        - ssldeps
        - docker

    - name: Add docker repository signing key
      become: true
      apt_key:
        id: 0EBFCD88
        url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
        state: present
      tags:
        - docker
    
    - name: Add docker repository
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
      tags:
        - docker
    
    - name: Install docker packages
      become: true
      apt:
        name: "docker-ce"
        state: present
        update_cache: yes
      tags:
        - docker
  
    - name: Install docker-compose
      become: true
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-{{ ansible_architecture }}"
        dest: /usr/local/bin/docker-compose
        force: yes
        owner: root
        group: root
        mode: 0755
      tags:
        - docker_compose
    
    - name: Install pip to be able to setup python packages
      become: true
      apt:
        name: python3-pip
        state: present
        update_cache: no
      tags:
        - ansible-docker
    
    - name: Install pip dependency for ansible docker module
      become: true
      pip:
        name: docker>=3.5
        state: present
      tags:
        - ansible-docker
    
    - name: Install pip dependency for ansible docker compose module
      become: true
      pip:
        name: docker-compose
        state: present
      tags:
        - ansible-docker