---

    - name: Make sure there are no old docker versions around
      become: true
      apt:
        name: "{{ deprecated_docker_pkg }}"
        state: absent
      tags:
        - docker
      
    - name: Install prerequisites for SSL repositories
      become: true
      apt:
        name: "{{ ssl_deps }}"
        state: present
        update_cache: yes
      tags:
        - ssldeps
        - docker

    - name: Add docker repository signing key
      become: true
      apt_key:
        id: 0EBFCD88
        url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
        state: present
      tags:
        - docker
    
    - name: Add docker repository
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes
      tags:
        - docker
    
    - name: Install docker packages
      become: true
      apt:
        name: "docker-ce"
        state: present
        update_cache: yes
      tags:
        - docker