---      
    - name: Install prerequisites for SSL repositories
      apt:
        name: "{{ ssl_deps }}"
        state: present
        update_cache: yes
      tags:
        - ssldep
        - vbox

    - name: "Add {{ software_name }} repository signing key"
      apt_key:
        url: "{{ item.key.key_url }}"
        state: present
      with_items: "{{ repositories }}"
      tags:
        - vbox
    
    - name: "Add {{ software_name }} repository"
      apt_repository:
        repo: "{{ item.repo_url }}"
        state: present
        update_cache: yes
      with_items: "{{ repositories }}"
      tags:
        - vbox
    
    - name: "Install {{ software_name }} packages"
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      register: aptdbg
      tags:
        - vbox
    
    - debug:
        msg: "{% if 'stdout_lines' in aptdbg %}{{ aptdbg.stdout_lines[-1] }}{% else %}Nothing was done{% endif %}"
      tags:
        - vbox